name: PR Test

on:
  pull_request:
      branches:
           - main

jobs:
    Run:
        runs-on: [ubuntu-latest] # 최신 우분투 가상환경 사용
        strategy:
          matrix:
            node-version: [14.x, 16.x] # ".x" 로 최신 버전도 사용하고 직접 버전 지정도 가능하다
        steps:
          - name: test code
            run: |
              npm install &&
              npm test
          - name: ==== fail ====
            uses: actions/github-script@v6
            with:
              github-token: ${{github.token}}  // github token을 선언해준다
              script: |
                const ref = "${{github.ref}}"
                const pull_number = Number(ref.split("/")[2])
                await github.pulls.createReview({
                  ...context.repo,
                  pull_number,
                  body:"테스트코드를 다시 확인해주세요. ",
                  event: "REQUEST_CHANGES"
                })
                await github.pulls.update({
                  ...context.repo,
                  pull_number,
                  state: "closed"
                })
            if: failure()
